name: Run it on action


on:  
  workflow_dispatch:
  schedule:
    - cron: 15 8,20 * * *
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Tieba Checkin
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Run
        run: |
          if [ '${{ secrets.BDUSS }}' != '' ]; then sed -i "s/xxxxx/${{ secrets.BDUSS }}/" tieba.php; fi
          php tieba.php
